[mypy]
plugins = pydantic.mypy
ignore_missing_imports = False
disallow_untyped_defs = True

[mypy-deepdiff.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True

[mypy-ffmpeg.*]
ignore_missing_imports = True

[mypy-langchain_community.*]
ignore_missing_imports = True

[mypy-neomodel.*]
ignore_missing_imports = True

[mypy-pytz.*]
ignore_missing_imports = True

[mypy-llama_index.*]
ignore_missing_imports = True

[mypy-jsonpickle.*]
ignore_missing_imports = True
