from typing import Literal

ALLOWED_INDUSTRIES = Literal[
    "Fashion",
    "Beauty",
    "Love & Dating",
    "Daily Life",
    "Dance",
    "Travel",
    "Food & Beverage",
    "Gaming",
    "DIY & Life Hacks",
    "Auto",
    "Health",
    "Science & Education",
    "Fitness",
    "Comedy",
    "Art",
    "Sport",
    "Family & Parenting",
    "Home & Garden",
    "Animals",
    "Outdoor Activities",
    "Baby & Maternity",
    "Household Appliances",
    "Home Supplies",
    "Books, Magazines & Audio",
    "Food & Beverages",
    "Beauty & Personal Care",
    "Fashion Accessories",
    "Sports & Outdoor",
    "Menswear & Underwear",
    "Jewelry Accessories & Derivatives",
    "Womenswear & Underwear",
    "Phones & Electronics",
    "Toys & Hobbies",
    "Kitchenware",
    "Shoes",
    "Home Improvement",
    "Luggage & Bags",
    "Automotive & Motorcycle",
    "Computers & Office Equipment",
    "Furniture",
    "Muslim Fashion",
    "Collectibles",
    "Textiles & Soft Furnishings",
    "Pet Supplies",
    "Kids' Fashion",
]


# ALLOWED_INDUSTRIES = Literal[
#     "Gaming",
#     "Shopping & Retail",
#     "Art",
#     "Beauty/Fashion",
#     "Media & Entertainment",
#     "Beauty",
#     "Personal Blog",
#     "Shopping/Retail",
#     "Public Figure",
#     "Clothing & Accessories",
#     "Others",
#     "Home, Furniture & Appliances",
#     "Machinery & Equipment",
#     "Electronics",
#     "Baby",
#     "Food & Beverage",
#     "TikTok Shop Multi-Channel Network (MCN)",
#     "Automotive & Transportation",
#     "Pets",
#     "Pets/Animals",
#     "Art & Crafts",
#     "Health & Wellness",
#     "Food/Cooking",
#     "Real Estate",
#     "Education & Training",
#     "Travel & Tourism",
#     "Professional Services",
#     "Finance & Investing",
#     "Other",
#     "Government/Politics",
#     "Public Administration",
#     "Sports, Fitness & Outdoors",
#     "Travel/Resort",
#     "Education",
#     "Restaurants & Bars",
#     "Software & Apps",
#     "Media",
#     "Medical/Health",
#     "Sports/Fitness",
#     "Music/Dance",
#     "Brand",
#     "Entertainment",
#     "NGO",
#     "Consultant/Service",
#     "LIVE Creator Networks",
#     "IT/High Tech",
# ]
